# Generated by Django 2.0.9 on 2018-10-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0007_registerpackageinfo_package_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerpackageinfo',
            name='noofpeople',
        ),
        migrations.AlterField(
            model_name='packagecosts',
            name='packagename',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
