# Generated by Django 2.0.9 on 2018-10-19 09:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0008_auto_20181017_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerpackageinfo',
            name='user_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
